### ISSUE TITLE
Please add a licence to the repository

### ISSUE THREAD

**Issue by cstrobbe** [stevefaulkner/wcagparsing#7]
Could you please add a licence to the repository? Without a licence, the code is fully copyrighted. As a consequence, anyone who wants to reuse or modify the code needs to ask permission in advance.

This is, to my knowledge, the general rule with source code (or any other "creative works"): if no open-source licence is specified, the work is not open source but fully copyrighted.

**Comment by stevefaulkner** [comment]
fixed by #8
